### ISSUE TITLE
libsystemd-journal merged on some distributions

### ISSUE THREAD

**Issue by adlerweb** [tuxmaster/gpsd-tcp#1]
The package currently depends on libsystemd-journal, this was however merged into libsystemd on several distributions. I had to replace the dependency to get the package compile on arch linux

--- a/gpsd-tcp/gpsd-tcp.pro
+++ b/gpsd-tcp/gpsd-tcp.pro
@@ -5,7 +5,7 @@ TARGET          = gpsd-tcp
 CONFIG                += link_pkgconfig
 QT             = core network

-PKGCONFIG      += libsystemd-journal
+PKGCONFIG      += libsystemd

 MOC_DIR                = tmp/moc
 OBJECTS_DIR    = tmp/obj

Ref:
https://bbs.archlinux.org/viewtopic.php?id=213563
https://www.freedesktop.org/software/systemd/man/sd-journal.html

**Comment by tuxmaster** [comment]
Fix in 8782f5331d53e60593207ea46143722dcf3373ad
